CREATE PROCEDURE [trusted].[GET_ORDERS_BY_PERSON]
(
	/*Returns Json*/
	@PERSON_ID INT,

	@MESSAGE_RESULT VARCHAR(256) OUTPUT,
	@SQL_ERROR_ID INT OUTPUT
)
AS
BEGIN

	SET NOCOUNT ON;

	IF @PERSON_ID IS NULL THROW 50001, '@PERSON_ID', 1;

	BEGIN TRY

		SELECT
			O.ORDER_ID orderId,
			O.ORDER_NAME orderName,
			O.ACTIVE_START orderDate,
			(SELECT
				OI.ORDER_ITEM_ID itemId,
				OI.NAME name,
				OI.COMMENTS comments
			FROM
				dbo.ORDER_ITEM OI
			WHERE
				O.ORDER_ID = OI.ORDER_ID
			FOR JSON PATH) items
		FROM
			dbo.[ORDER] O
		WHERE
			O.PERSON_ID = @PERSON_ID
		FOR JSON PATH;

		RETURN 200;

	END TRY
	BEGIN CATCH

		--DO SOME LOGGING AND GET ERROR ID
		SET @SQL_ERROR_ID = 1234;
		SET @MESSAGE_RESULT = (SELECT 'ERROR OCCURED AND HAS BEEN LOGGED');

		RETURN 500;

	END CATCH

END;
