CREATE TABLE [dbo].[ORDER_ITEM]
(
	[ORDER_ITEM_ID] INT NOT NULL IDENTITY(1,1), 
    [ORDER_ID] INT NOT NULL, 
    [NAME] VARCHAR(32) NOT NULL, 
    [COMMENTS] VARCHAR(256) NULL, 
    CONSTRAINT [PK_ORDER_ITEM] PRIMARY KEY ([ORDER_ITEM_ID])
)