CREATE PROCEDURE [open].[GET_ORDER]
(
	/*Returns Json*/
	/*Single Result*/

	@ORDER_ID INT,

	@SQL_ERROR_ID INT OUTPUT,
	@MESSAGE_RESULT VARCHAR(256) OUTPUT
)
AS
BEGIN
	
	SET NOCOUNT ON;
	
	IF @ORDER_ID IS NULL THROW 50001, '@ORDER_ID', 1;

	BEGIN TRY

		IF NOT EXISTS (SELECT 1 FROM dbo.[ORDER] WHERE ORDER_ID = @ORDER_ID) RETURN 404;

		SELECT
			O.ORDER_ID orderId,
			O.ORDER_NAME orderName,
			(SELECT
				OI.ORDER_ITEM_ID orderItemId,
				OI.NAME name,
				OI.COMMENTS comments
			FROM
				dbo.ORDER_ITEM OI
			WHERE
				O.ORDER_ID = OI.ORDER_ID FOR Json PATH) orderItems
		FROM
			dbo.[ORDER] O
		WHERE
			ORDER_ID = @ORDER_ID
		FOR Json PATH, WITHOUT_ARRAY_WRAPPER;
		
		RETURN 200;

	END TRY
	BEGIN CATCH
		
		SET @SQL_ERROR_ID = 1234;
		SET @MESSAGE_RESULT = 'AN ERROR OCCURED';

	END CATCH

END;